CREATE TABLE SPRINGMEMBER(
	ID VARCHAR2(50),
    PW VARCHAR2(300) NOT NULL,
	AUTH CHAR(1),
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "SPRINGMEMBER_PK" PRIMARY KEY(ID),
	CONSTRAINT "SPRINGMEMBER_CK" CHECK("AUTH" IN ('U','A'))
);


CREATE TABLE SPRINGBOARD(
	SEQ NUMBER NOT NULL,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000),
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	REFER NUMBER NOT NULL,
	READCOUNT NUMBER,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "SPRINGBOARD_PK" PRIMARY KEY(SEQ),
	CONSTRAINT "SPRINGBOARD_FK" FOREIGN KEY("ID") REFERENCES SPRINGMEMBER("ID")
);

CREATE SEQUENCE SPRINGBOARD_SEQ START WITH 1 INCREMENT BY 1;





